prometheus:
  url: http://prometheus.istio-system.svc.cluster.local
  port: 9090

rules:
  custom:
  #total istio requests per second
  
  - seriesQuery: 'istio_requests_total{reporter="destination", destination_workload_namespace="default", destination_workload="product"}'
    resources:
      overrides:
        destination_workload_namespace:
          resource: "namespace"
        destination_workload_name:
          resource: "deployment"
    name:
      as: "requests_per_second"
    metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>, reporter="destination"}[5m])) by (<<.GroupBy>>)'

  #istio request duration

  - seriesQuery: 'istio_request_duration_milliseconds_bucket{reporter="destination", destination_workload_namespace="default", destination_workload="product"}'
    resources:
      overrides:
        destination_workload_namespace:
          resource: "namespace"
        destination_workload:
          resource: "deployment"
    name:
      as: "request_duration_seconds_90ile"
    metricsQuery: 'sum(histogram_quantile(0.90, sum(irate(<<.Series>>{<<.LabelMatchers>>, reporter="destination"}[5m])) by (le,<<.GroupBy>>))) by (<<.GroupBy>>) / 1000'